name: 'Demo action'
description: 'Demo action'


inputs:
  randomTime:
    description: The maximum time
    required: true
  successRate:
    description: The random success rate between 1 and 10
    required: true

runs:
  using: composite
  steps:
    - name: Demo action
      
      shell: bash
      run: |
        echo "Random action using inputs time ${{ inputs.randomTime }} and success rate ${{ inputs.successRate }}"
        time=$(( $RANDOM % ${{ inputs.randomTime }} ))
        randomSuccessRate=$(( $RANDOM % 10 ))
        echo "Demo action using random time ${time} and random success rate ${randomSuccessRate}"
        sleep $time

        echo "Comparing random success rate ${randomSuccessRate} with input success rate ${{ inputs.successRate }}"

        if [ $randomSuccessRate -gt "${{ inputs.successRate }}" ]; then
          echo "Demo action is randomly failing time ${successRate} and ${{ inputs.successRate }}"  
          exit 1
        fi