name: PR demo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: pnpm install
      - run: pnpm test

  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ["lint", "unit tests", "typescript checks", "e2e tests"]
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ matrix.job }}

      - uses: ./.github/actions/demo-action
        with:
          randomTime: 100
          successRate: 7

  pr-deploy:
    name: PR deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: ./.github/actions/demo-action
        with:
          randomTime: 300
          successRate: 5
