name: PR demo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.28.0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile --ignore-scripts

      - run: pnpm test

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: junit test report
          path: junit.xml

  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ["lint", "typescript checks", "e2e tests"]
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ matrix.job }}

      - uses: ./.github/actions/demo-action
        with:
          randomTime: 100
          successRate: 7

  pr-deploy:
    name: PR deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: ./.github/actions/demo-action
        with:
          randomTime: 100
          successRate: 5
