name: PR demo

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'


jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          [
            'lint',
            'unit tests',
            'typescript checks',
            'e2e tests'
          ]
    steps:
      - uses: actions/checkout@v3.1.0

      - run: echo ${{ matrix.job }}

      - uses: ./.github/actions/demo-action
        with: 
          randomTime: 10
          randomSuccessRate: 10